# -*- coding: utf-8 -*-
"""prueba-colab-github.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LuDiNqqdmlQZqLpIxzqwr9RQXa5JJFwz

suma
"""

a=3
b=4

suma=a+b
print("suma=",suma)